server:
  cache:
    debounce-delay: 30
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
socketio:
  host: 0.0.0.0
  port: 8030
  worker-threads: 100
  allow-custom-requests: true
  upgrade-timeout: 1000000
  max-frame-payload-length: 1048576
  max-http-content-length: 1048576
  context: /ws
