// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MarkerDiffSnapshotVo.proto
// Protobuf Java Version: 4.33.0

package site.yuanshen.data.proto;

@com.google.protobuf.Generated
public final class MarkerDiffSnapshotVoOuterClass extends com.google.protobuf.GeneratedFile {
  private MarkerDiffSnapshotVoOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "MarkerDiffSnapshotVoOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MarkerDiffSnapshotVoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.yuanshen.data.proto.MarkerDiffSnapshotVo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 version = 1;</code>
     * @return The version.
     */
    long getVersion();

    /**
     * <code>uint64 id = 2;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>optional string linkage_id = 15;</code>
     * @return Whether the linkageId field is set.
     */
    boolean hasLinkageId();
    /**
     * <code>optional string linkage_id = 15;</code>
     * @return The linkageId.
     */
    java.lang.String getLinkageId();
    /**
     * <code>optional string linkage_id = 15;</code>
     * @return The bytes for linkageId.
     */
    com.google.protobuf.ByteString
        getLinkageIdBytes();
  }
  /**
   * Protobuf type {@code site.yuanshen.data.proto.MarkerDiffSnapshotVo}
   */
  public static final class MarkerDiffSnapshotVo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:site.yuanshen.data.proto.MarkerDiffSnapshotVo)
      MarkerDiffSnapshotVoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "MarkerDiffSnapshotVo");
    }
    // Use MarkerDiffSnapshotVo.newBuilder() to construct.
    private MarkerDiffSnapshotVo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MarkerDiffSnapshotVo() {
      linkageId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.class, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_ = 0L;
    /**
     * <code>uint64 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_ = 0L;
    /**
     * <code>uint64 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int LINKAGE_ID_FIELD_NUMBER = 15;
    @SuppressWarnings("serial")
    private volatile java.lang.Object linkageId_ = "";
    /**
     * <code>optional string linkage_id = 15;</code>
     * @return Whether the linkageId field is set.
     */
    @java.lang.Override
    public boolean hasLinkageId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string linkage_id = 15;</code>
     * @return The linkageId.
     */
    @java.lang.Override
    public java.lang.String getLinkageId() {
      java.lang.Object ref = linkageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        linkageId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string linkage_id = 15;</code>
     * @return The bytes for linkageId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLinkageIdBytes() {
      java.lang.Object ref = linkageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        linkageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0L) {
        output.writeUInt64(1, version_);
      }
      if (id_ != 0L) {
        output.writeUInt64(2, id_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 15, linkageId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, version_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, id_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(15, linkageId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo)) {
        return super.equals(obj);
      }
      site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo other = (site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (getId()
          != other.getId()) return false;
      if (hasLinkageId() != other.hasLinkageId()) return false;
      if (hasLinkageId()) {
        if (!getLinkageId()
            .equals(other.getLinkageId())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVersion());
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      if (hasLinkageId()) {
        hash = (37 * hash) + LINKAGE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getLinkageId().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.yuanshen.data.proto.MarkerDiffSnapshotVo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.yuanshen.data.proto.MarkerDiffSnapshotVo)
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.class, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder.class);
      }

      // Construct using site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        version_ = 0L;
        id_ = 0L;
        linkageId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_descriptor;
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo getDefaultInstanceForType() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.getDefaultInstance();
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo build() {
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo buildPartial() {
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo result = new site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.version_ = version_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.id_ = id_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.linkageId_ = linkageId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo) {
          return mergeFrom((site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo other) {
        if (other == site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.getDefaultInstance()) return this;
        if (other.getVersion() != 0L) {
          setVersion(other.getVersion());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.hasLinkageId()) {
          linkageId_ = other.linkageId_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                version_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                id_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 122: {
                linkageId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 122
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long version_ ;
      /**
       * <code>uint64 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public long getVersion() {
        return version_;
      }
      /**
       * <code>uint64 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(long value) {

        version_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0L;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <code>uint64 id = 2;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>uint64 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object linkageId_ = "";
      /**
       * <code>optional string linkage_id = 15;</code>
       * @return Whether the linkageId field is set.
       */
      public boolean hasLinkageId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string linkage_id = 15;</code>
       * @return The linkageId.
       */
      public java.lang.String getLinkageId() {
        java.lang.Object ref = linkageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          linkageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string linkage_id = 15;</code>
       * @return The bytes for linkageId.
       */
      public com.google.protobuf.ByteString
          getLinkageIdBytes() {
        java.lang.Object ref = linkageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          linkageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string linkage_id = 15;</code>
       * @param value The linkageId to set.
       * @return This builder for chaining.
       */
      public Builder setLinkageId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        linkageId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string linkage_id = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearLinkageId() {
        linkageId_ = getDefaultInstance().getLinkageId();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string linkage_id = 15;</code>
       * @param value The bytes for linkageId to set.
       * @return This builder for chaining.
       */
      public Builder setLinkageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        linkageId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:site.yuanshen.data.proto.MarkerDiffSnapshotVo)
    }

    // @@protoc_insertion_point(class_scope:site.yuanshen.data.proto.MarkerDiffSnapshotVo)
    private static final site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo();
    }

    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MarkerDiffSnapshotVo>
        PARSER = new com.google.protobuf.AbstractParser<MarkerDiffSnapshotVo>() {
      @java.lang.Override
      public MarkerDiffSnapshotVo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MarkerDiffSnapshotVo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MarkerDiffSnapshotVo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MarkerDiffSnapshotVoListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.yuanshen.data.proto.MarkerDiffSnapshotVoList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    java.util.List<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo> 
        getSnapshotsList();
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo getSnapshots(int index);
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    int getSnapshotsCount();
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    java.util.List<? extends site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder> 
        getSnapshotsOrBuilderList();
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder getSnapshotsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code site.yuanshen.data.proto.MarkerDiffSnapshotVoList}
   */
  public static final class MarkerDiffSnapshotVoList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:site.yuanshen.data.proto.MarkerDiffSnapshotVoList)
      MarkerDiffSnapshotVoListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "MarkerDiffSnapshotVoList");
    }
    // Use MarkerDiffSnapshotVoList.newBuilder() to construct.
    private MarkerDiffSnapshotVoList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MarkerDiffSnapshotVoList() {
      snapshots_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.class, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.Builder.class);
    }

    public static final int SNAPSHOTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo> snapshots_;
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    @java.lang.Override
    public java.util.List<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo> getSnapshotsList() {
      return snapshots_;
    }
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder> 
        getSnapshotsOrBuilderList() {
      return snapshots_;
    }
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    @java.lang.Override
    public int getSnapshotsCount() {
      return snapshots_.size();
    }
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    @java.lang.Override
    public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo getSnapshots(int index) {
      return snapshots_.get(index);
    }
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    @java.lang.Override
    public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder getSnapshotsOrBuilder(
        int index) {
      return snapshots_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < snapshots_.size(); i++) {
        output.writeMessage(1, snapshots_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < snapshots_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, snapshots_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList)) {
        return super.equals(obj);
      }
      site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList other = (site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList) obj;

      if (!getSnapshotsList()
          .equals(other.getSnapshotsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSnapshotsCount() > 0) {
        hash = (37 * hash) + SNAPSHOTS_FIELD_NUMBER;
        hash = (53 * hash) + getSnapshotsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.yuanshen.data.proto.MarkerDiffSnapshotVoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.yuanshen.data.proto.MarkerDiffSnapshotVoList)
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.class, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.Builder.class);
      }

      // Construct using site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (snapshotsBuilder_ == null) {
          snapshots_ = java.util.Collections.emptyList();
        } else {
          snapshots_ = null;
          snapshotsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_descriptor;
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList getDefaultInstanceForType() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.getDefaultInstance();
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList build() {
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList buildPartial() {
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList result = new site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList result) {
        if (snapshotsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            snapshots_ = java.util.Collections.unmodifiableList(snapshots_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.snapshots_ = snapshots_;
        } else {
          result.snapshots_ = snapshotsBuilder_.build();
        }
      }

      private void buildPartial0(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList) {
          return mergeFrom((site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList other) {
        if (other == site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.getDefaultInstance()) return this;
        if (snapshotsBuilder_ == null) {
          if (!other.snapshots_.isEmpty()) {
            if (snapshots_.isEmpty()) {
              snapshots_ = other.snapshots_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSnapshotsIsMutable();
              snapshots_.addAll(other.snapshots_);
            }
            onChanged();
          }
        } else {
          if (!other.snapshots_.isEmpty()) {
            if (snapshotsBuilder_.isEmpty()) {
              snapshotsBuilder_.dispose();
              snapshotsBuilder_ = null;
              snapshots_ = other.snapshots_;
              bitField0_ = (bitField0_ & ~0x00000001);
              snapshotsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetSnapshotsFieldBuilder() : null;
            } else {
              snapshotsBuilder_.addAllMessages(other.snapshots_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo m =
                    input.readMessage(
                        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.parser(),
                        extensionRegistry);
                if (snapshotsBuilder_ == null) {
                  ensureSnapshotsIsMutable();
                  snapshots_.add(m);
                } else {
                  snapshotsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo> snapshots_ =
        java.util.Collections.emptyList();
      private void ensureSnapshotsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          snapshots_ = new java.util.ArrayList<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo>(snapshots_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder> snapshotsBuilder_;

      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public java.util.List<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo> getSnapshotsList() {
        if (snapshotsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(snapshots_);
        } else {
          return snapshotsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public int getSnapshotsCount() {
        if (snapshotsBuilder_ == null) {
          return snapshots_.size();
        } else {
          return snapshotsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo getSnapshots(int index) {
        if (snapshotsBuilder_ == null) {
          return snapshots_.get(index);
        } else {
          return snapshotsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder setSnapshots(
          int index, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo value) {
        if (snapshotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnapshotsIsMutable();
          snapshots_.set(index, value);
          onChanged();
        } else {
          snapshotsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder setSnapshots(
          int index, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder builderForValue) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          snapshots_.set(index, builderForValue.build());
          onChanged();
        } else {
          snapshotsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder addSnapshots(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo value) {
        if (snapshotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnapshotsIsMutable();
          snapshots_.add(value);
          onChanged();
        } else {
          snapshotsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder addSnapshots(
          int index, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo value) {
        if (snapshotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnapshotsIsMutable();
          snapshots_.add(index, value);
          onChanged();
        } else {
          snapshotsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder addSnapshots(
          site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder builderForValue) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          snapshots_.add(builderForValue.build());
          onChanged();
        } else {
          snapshotsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder addSnapshots(
          int index, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder builderForValue) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          snapshots_.add(index, builderForValue.build());
          onChanged();
        } else {
          snapshotsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder addAllSnapshots(
          java.lang.Iterable<? extends site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo> values) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, snapshots_);
          onChanged();
        } else {
          snapshotsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder clearSnapshots() {
        if (snapshotsBuilder_ == null) {
          snapshots_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          snapshotsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder removeSnapshots(int index) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          snapshots_.remove(index);
          onChanged();
        } else {
          snapshotsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder getSnapshotsBuilder(
          int index) {
        return internalGetSnapshotsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder getSnapshotsOrBuilder(
          int index) {
        if (snapshotsBuilder_ == null) {
          return snapshots_.get(index);  } else {
          return snapshotsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public java.util.List<? extends site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder> 
           getSnapshotsOrBuilderList() {
        if (snapshotsBuilder_ != null) {
          return snapshotsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(snapshots_);
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder addSnapshotsBuilder() {
        return internalGetSnapshotsFieldBuilder().addBuilder(
            site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.getDefaultInstance());
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder addSnapshotsBuilder(
          int index) {
        return internalGetSnapshotsFieldBuilder().addBuilder(
            index, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.getDefaultInstance());
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public java.util.List<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder> 
           getSnapshotsBuilderList() {
        return internalGetSnapshotsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder> 
          internalGetSnapshotsFieldBuilder() {
        if (snapshotsBuilder_ == null) {
          snapshotsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder>(
                  snapshots_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          snapshots_ = null;
        }
        return snapshotsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:site.yuanshen.data.proto.MarkerDiffSnapshotVoList)
    }

    // @@protoc_insertion_point(class_scope:site.yuanshen.data.proto.MarkerDiffSnapshotVoList)
    private static final site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList();
    }

    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MarkerDiffSnapshotVoList>
        PARSER = new com.google.protobuf.AbstractParser<MarkerDiffSnapshotVoList>() {
      @java.lang.Override
      public MarkerDiffSnapshotVoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MarkerDiffSnapshotVoList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MarkerDiffSnapshotVoList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032MarkerDiffSnapshotVo.proto\022\030site.yuans" +
      "hen.data.proto\"[\n\024MarkerDiffSnapshotVo\022\017" +
      "\n\007version\030\001 \001(\004\022\n\n\002id\030\002 \001(\004\022\027\n\nlinkage_i" +
      "d\030\017 \001(\tH\000\210\001\001B\r\n\013_linkage_id\"]\n\030MarkerDif" +
      "fSnapshotVoList\022A\n\tsnapshots\030\001 \003(\0132..sit" +
      "e.yuanshen.data.proto.MarkerDiffSnapshot" +
      "Vob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_descriptor,
        new java.lang.String[] { "Version", "Id", "LinkageId", });
    internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_descriptor,
        new java.lang.String[] { "Snapshots", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
