// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MarkerVoList.proto
// Protobuf Java Version: 4.33.0

package site.yuanshen.data.proto;

@com.google.protobuf.Generated
public final class MarkerVoListOuterClass extends com.google.protobuf.GeneratedFile {
  private MarkerVoListOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "MarkerVoListOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MarkerVoListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.yuanshen.data.proto.MarkerVoList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
     */
    java.util.List<site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo> 
        getMarkersList();
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
     */
    site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo getMarkers(int index);
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
     */
    int getMarkersCount();
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
     */
    java.util.List<? extends site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVoOrBuilder> 
        getMarkersOrBuilderList();
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
     */
    site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVoOrBuilder getMarkersOrBuilder(
        int index);

    /**
     * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
     */
    int getUsersCount();
    /**
     * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
     */
    boolean containsUsers(
        long key);
    /**
     * Use {@link #getUsersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo>
    getUsers();
    /**
     * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
     */
    java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo>
    getUsersMap();
    /**
     * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
     */
    /* nullable */
site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo getUsersOrDefault(
        long key,
        /* nullable */
site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo defaultValue);
    /**
     * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
     */
    site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo getUsersOrThrow(
        long key);
  }
  /**
   * Protobuf type {@code site.yuanshen.data.proto.MarkerVoList}
   */
  public static final class MarkerVoList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:site.yuanshen.data.proto.MarkerVoList)
      MarkerVoListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "MarkerVoList");
    }
    // Use MarkerVoList.newBuilder() to construct.
    private MarkerVoList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MarkerVoList() {
      markers_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return site.yuanshen.data.proto.MarkerVoListOuterClass.internal_static_site_yuanshen_data_proto_MarkerVoList_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetUsers();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return site.yuanshen.data.proto.MarkerVoListOuterClass.internal_static_site_yuanshen_data_proto_MarkerVoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList.class, site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList.Builder.class);
    }

    public static final int MARKERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo> markers_;
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
     */
    @java.lang.Override
    public java.util.List<site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo> getMarkersList() {
      return markers_;
    }
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVoOrBuilder> 
        getMarkersOrBuilderList() {
      return markers_;
    }
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
     */
    @java.lang.Override
    public int getMarkersCount() {
      return markers_.size();
    }
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
     */
    @java.lang.Override
    public site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo getMarkers(int index) {
      return markers_.get(index);
    }
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
     */
    @java.lang.Override
    public site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVoOrBuilder getMarkersOrBuilder(
        int index) {
      return markers_.get(index);
    }

    public static final int USERS_FIELD_NUMBER = 2;
    private static final class UsersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo>newDefaultInstance(
                  site.yuanshen.data.proto.MarkerVoListOuterClass.internal_static_site_yuanshen_data_proto_MarkerVoList_UsersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.UINT64,
                  0L,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> users_;
    private com.google.protobuf.MapField<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo>
    internalGetUsers() {
      if (users_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UsersDefaultEntryHolder.defaultEntry);
      }
      return users_;
    }
    public int getUsersCount() {
      return internalGetUsers().getMap().size();
    }
    /**
     * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
     */
    @java.lang.Override
    public boolean containsUsers(
        long key) {

      return internalGetUsers().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUsersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> getUsers() {
      return getUsersMap();
    }
    /**
     * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> getUsersMap() {
      return internalGetUsers().getMap();
    }
    /**
     * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo getUsersOrDefault(
        long key,
        /* nullable */
site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo defaultValue) {

      java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> map =
          internalGetUsers().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
     */
    @java.lang.Override
    public site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo getUsersOrThrow(
        long key) {

      java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> map =
          internalGetUsers().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < markers_.size(); i++) {
        output.writeMessage(1, markers_.get(i));
      }
      com.google.protobuf.GeneratedMessage
        .serializeLongMapTo(
          output,
          internalGetUsers(),
          UsersDefaultEntryHolder.defaultEntry,
          2);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < markers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, markers_.get(i));
      }
      for (java.util.Map.Entry<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> entry
           : internalGetUsers().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo>
        users__ = UsersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, users__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList)) {
        return super.equals(obj);
      }
      site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList other = (site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList) obj;

      if (!getMarkersList()
          .equals(other.getMarkersList())) return false;
      if (!internalGetUsers().equals(
          other.internalGetUsers())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMarkersCount() > 0) {
        hash = (37 * hash) + MARKERS_FIELD_NUMBER;
        hash = (53 * hash) + getMarkersList().hashCode();
      }
      if (!internalGetUsers().getMap().isEmpty()) {
        hash = (37 * hash) + USERS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetUsers().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.yuanshen.data.proto.MarkerVoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.yuanshen.data.proto.MarkerVoList)
        site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return site.yuanshen.data.proto.MarkerVoListOuterClass.internal_static_site_yuanshen_data_proto_MarkerVoList_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetUsers();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableUsers();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return site.yuanshen.data.proto.MarkerVoListOuterClass.internal_static_site_yuanshen_data_proto_MarkerVoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList.class, site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList.Builder.class);
      }

      // Construct using site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (markersBuilder_ == null) {
          markers_ = java.util.Collections.emptyList();
        } else {
          markers_ = null;
          markersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableUsers().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return site.yuanshen.data.proto.MarkerVoListOuterClass.internal_static_site_yuanshen_data_proto_MarkerVoList_descriptor;
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList getDefaultInstanceForType() {
        return site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList.getDefaultInstance();
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList build() {
        site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList buildPartial() {
        site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList result = new site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList result) {
        if (markersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            markers_ = java.util.Collections.unmodifiableList(markers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.markers_ = markers_;
        } else {
          result.markers_ = markersBuilder_.build();
        }
      }

      private void buildPartial0(site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.users_ = internalGetUsers().build(UsersDefaultEntryHolder.defaultEntry);
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList) {
          return mergeFrom((site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList other) {
        if (other == site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList.getDefaultInstance()) return this;
        if (markersBuilder_ == null) {
          if (!other.markers_.isEmpty()) {
            if (markers_.isEmpty()) {
              markers_ = other.markers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMarkersIsMutable();
              markers_.addAll(other.markers_);
            }
            onChanged();
          }
        } else {
          if (!other.markers_.isEmpty()) {
            if (markersBuilder_.isEmpty()) {
              markersBuilder_.dispose();
              markersBuilder_ = null;
              markers_ = other.markers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              markersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetMarkersFieldBuilder() : null;
            } else {
              markersBuilder_.addAllMessages(other.markers_);
            }
          }
        }
        internalGetMutableUsers().mergeFrom(
            other.internalGetUsers());
        bitField0_ |= 0x00000002;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo m =
                    input.readMessage(
                        site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.parser(),
                        extensionRegistry);
                if (markersBuilder_ == null) {
                  ensureMarkersIsMutable();
                  markers_.add(m);
                } else {
                  markersBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 18: {
                com.google.protobuf.MapEntry<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo>
                users__ = input.readMessage(
                    UsersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableUsers().ensureBuilderMap().put(
                    users__.getKey(), users__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo> markers_ =
        java.util.Collections.emptyList();
      private void ensureMarkersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          markers_ = new java.util.ArrayList<site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo>(markers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo, site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.Builder, site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVoOrBuilder> markersBuilder_;

      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public java.util.List<site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo> getMarkersList() {
        if (markersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(markers_);
        } else {
          return markersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public int getMarkersCount() {
        if (markersBuilder_ == null) {
          return markers_.size();
        } else {
          return markersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo getMarkers(int index) {
        if (markersBuilder_ == null) {
          return markers_.get(index);
        } else {
          return markersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public Builder setMarkers(
          int index, site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo value) {
        if (markersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarkersIsMutable();
          markers_.set(index, value);
          onChanged();
        } else {
          markersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public Builder setMarkers(
          int index, site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.Builder builderForValue) {
        if (markersBuilder_ == null) {
          ensureMarkersIsMutable();
          markers_.set(index, builderForValue.build());
          onChanged();
        } else {
          markersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public Builder addMarkers(site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo value) {
        if (markersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarkersIsMutable();
          markers_.add(value);
          onChanged();
        } else {
          markersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public Builder addMarkers(
          int index, site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo value) {
        if (markersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarkersIsMutable();
          markers_.add(index, value);
          onChanged();
        } else {
          markersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public Builder addMarkers(
          site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.Builder builderForValue) {
        if (markersBuilder_ == null) {
          ensureMarkersIsMutable();
          markers_.add(builderForValue.build());
          onChanged();
        } else {
          markersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public Builder addMarkers(
          int index, site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.Builder builderForValue) {
        if (markersBuilder_ == null) {
          ensureMarkersIsMutable();
          markers_.add(index, builderForValue.build());
          onChanged();
        } else {
          markersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public Builder addAllMarkers(
          java.lang.Iterable<? extends site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo> values) {
        if (markersBuilder_ == null) {
          ensureMarkersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, markers_);
          onChanged();
        } else {
          markersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public Builder clearMarkers() {
        if (markersBuilder_ == null) {
          markers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          markersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public Builder removeMarkers(int index) {
        if (markersBuilder_ == null) {
          ensureMarkersIsMutable();
          markers_.remove(index);
          onChanged();
        } else {
          markersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.Builder getMarkersBuilder(
          int index) {
        return internalGetMarkersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVoOrBuilder getMarkersOrBuilder(
          int index) {
        if (markersBuilder_ == null) {
          return markers_.get(index);  } else {
          return markersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public java.util.List<? extends site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVoOrBuilder> 
           getMarkersOrBuilderList() {
        if (markersBuilder_ != null) {
          return markersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(markers_);
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.Builder addMarkersBuilder() {
        return internalGetMarkersFieldBuilder().addBuilder(
            site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.getDefaultInstance());
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.Builder addMarkersBuilder(
          int index) {
        return internalGetMarkersFieldBuilder().addBuilder(
            index, site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.getDefaultInstance());
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerVo markers = 1;</code>
       */
      public java.util.List<site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.Builder> 
           getMarkersBuilderList() {
        return internalGetMarkersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo, site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.Builder, site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVoOrBuilder> 
          internalGetMarkersFieldBuilder() {
        if (markersBuilder_ == null) {
          markersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo, site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVo.Builder, site.yuanshen.data.proto.MarkerVoOuterClass.MarkerVoOrBuilder>(
                  markers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          markers_ = null;
        }
        return markersBuilder_;
      }

      private static final class UsersConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVoOrBuilder, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> {
        @java.lang.Override
        public site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo build(site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVoOrBuilder val) {
          if (val instanceof site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo) { return (site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo) val; }
          return ((site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> defaultEntry() {
          return UsersDefaultEntryHolder.defaultEntry;
        }
      };
      private static final UsersConverter usersConverter = new UsersConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVoOrBuilder, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.Builder> users_;
      private com.google.protobuf.MapFieldBuilder<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVoOrBuilder, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.Builder>
          internalGetUsers() {
        if (users_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(usersConverter);
        }
        return users_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVoOrBuilder, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.Builder>
          internalGetMutableUsers() {
        if (users_ == null) {
          users_ = new com.google.protobuf.MapFieldBuilder<>(usersConverter);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return users_;
      }
      public int getUsersCount() {
        return internalGetUsers().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
       */
      @java.lang.Override
      public boolean containsUsers(
          long key) {

        return internalGetUsers().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getUsersMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> getUsers() {
        return getUsersMap();
      }
      /**
       * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> getUsersMap() {
        return internalGetUsers().getImmutableMap();
      }
      /**
       * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
       */
      @java.lang.Override
      public /* nullable */
site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo getUsersOrDefault(
          long key,
          /* nullable */
site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo defaultValue) {

        java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVoOrBuilder> map = internalGetMutableUsers().ensureBuilderMap();
        return map.containsKey(key) ? usersConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
       */
      @java.lang.Override
      public site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo getUsersOrThrow(
          long key) {

        java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVoOrBuilder> map = internalGetMutableUsers().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return usersConverter.build(map.get(key));
      }
      public Builder clearUsers() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableUsers().clear();
        return this;
      }
      /**
       * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
       */
      public Builder removeUsers(
          long key) {

        internalGetMutableUsers().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo>
          getMutableUsers() {
        bitField0_ |= 0x00000002;
        return internalGetMutableUsers().ensureMessageMap();
      }
      /**
       * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
       */
      public Builder putUsers(
          long key,
          site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo value) {

        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableUsers().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
       */
      public Builder putAllUsers(
          java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> values) {
        for (java.util.Map.Entry<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableUsers().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;uint64, .site.yuanshen.data.proto.SysUserSmallVo&gt; users = 2;</code>
       */
      public site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.Builder putUsersBuilderIfAbsent(
          long key) {
        java.util.Map<java.lang.Long, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVoOrBuilder> builderMap = internalGetMutableUsers().ensureBuilderMap();
        site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVoOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo) {
          entry = ((site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.Builder) entry;
      }

      // @@protoc_insertion_point(builder_scope:site.yuanshen.data.proto.MarkerVoList)
    }

    // @@protoc_insertion_point(class_scope:site.yuanshen.data.proto.MarkerVoList)
    private static final site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList();
    }

    public static site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MarkerVoList>
        PARSER = new com.google.protobuf.AbstractParser<MarkerVoList>() {
      @java.lang.Override
      public MarkerVoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MarkerVoList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MarkerVoList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public site.yuanshen.data.proto.MarkerVoListOuterClass.MarkerVoList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_yuanshen_data_proto_MarkerVoList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_site_yuanshen_data_proto_MarkerVoList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_yuanshen_data_proto_MarkerVoList_UsersEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_site_yuanshen_data_proto_MarkerVoList_UsersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MarkerVoList.proto\022\030site.yuanshen.data" +
      ".proto\032\016MarkerVo.proto\032\024SysUserSmallVo.p" +
      "roto\"\335\001\n\014MarkerVoList\0223\n\007markers\030\001 \003(\0132\"" +
      ".site.yuanshen.data.proto.MarkerVo\022@\n\005us" +
      "ers\030\002 \003(\01321.site.yuanshen.data.proto.Mar" +
      "kerVoList.UsersEntry\032V\n\nUsersEntry\022\013\n\003ke" +
      "y\030\001 \001(\004\0227\n\005value\030\002 \001(\0132(.site.yuanshen.d" +
      "ata.proto.SysUserSmallVo:\0028\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          site.yuanshen.data.proto.MarkerVoOuterClass.getDescriptor(),
          site.yuanshen.data.proto.SysUserSmallVoOuterClass.getDescriptor(),
        });
    internal_static_site_yuanshen_data_proto_MarkerVoList_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_site_yuanshen_data_proto_MarkerVoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_site_yuanshen_data_proto_MarkerVoList_descriptor,
        new java.lang.String[] { "Markers", "Users", });
    internal_static_site_yuanshen_data_proto_MarkerVoList_UsersEntry_descriptor =
      internal_static_site_yuanshen_data_proto_MarkerVoList_descriptor.getNestedType(0);
    internal_static_site_yuanshen_data_proto_MarkerVoList_UsersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_site_yuanshen_data_proto_MarkerVoList_UsersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    site.yuanshen.data.proto.MarkerVoOuterClass.getDescriptor();
    site.yuanshen.data.proto.SysUserSmallVoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
