// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MarkerDiffSnapshotVo.proto

package site.yuanshen.data.proto;

public final class MarkerDiffSnapshotVoOuterClass {
  private MarkerDiffSnapshotVoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MarkerDiffSnapshotVoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.yuanshen.data.proto.MarkerDiffSnapshotVo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 version = 1;</code>
     * @return The version.
     */
    long getVersion();

    /**
     * <code>uint64 id = 2;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * Protobuf type {@code site.yuanshen.data.proto.MarkerDiffSnapshotVo}
   */
  public  static final class MarkerDiffSnapshotVo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.yuanshen.data.proto.MarkerDiffSnapshotVo)
      MarkerDiffSnapshotVoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MarkerDiffSnapshotVo.newBuilder() to construct.
    private MarkerDiffSnapshotVo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MarkerDiffSnapshotVo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MarkerDiffSnapshotVo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MarkerDiffSnapshotVo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readUInt64();
              break;
            }
            case 16: {

              id_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.class, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_;
    /**
     * <code>uint64 version = 1;</code>
     * @return The version.
     */
    public long getVersion() {
      return version_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <code>uint64 id = 2;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0L) {
        output.writeUInt64(1, version_);
      }
      if (id_ != 0L) {
        output.writeUInt64(2, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, version_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo)) {
        return super.equals(obj);
      }
      site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo other = (site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVersion());
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.yuanshen.data.proto.MarkerDiffSnapshotVo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.yuanshen.data.proto.MarkerDiffSnapshotVo)
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.class, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder.class);
      }

      // Construct using site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0L;

        id_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_descriptor;
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo getDefaultInstanceForType() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.getDefaultInstance();
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo build() {
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo buildPartial() {
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo result = new site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo(this);
        result.version_ = version_;
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo) {
          return mergeFrom((site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo other) {
        if (other == site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.getDefaultInstance()) return this;
        if (other.getVersion() != 0L) {
          setVersion(other.getVersion());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long version_ ;
      /**
       * <code>uint64 version = 1;</code>
       * @return The version.
       */
      public long getVersion() {
        return version_;
      }
      /**
       * <code>uint64 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(long value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0L;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <code>uint64 id = 2;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>uint64 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:site.yuanshen.data.proto.MarkerDiffSnapshotVo)
    }

    // @@protoc_insertion_point(class_scope:site.yuanshen.data.proto.MarkerDiffSnapshotVo)
    private static final site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo();
    }

    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MarkerDiffSnapshotVo>
        PARSER = new com.google.protobuf.AbstractParser<MarkerDiffSnapshotVo>() {
      @java.lang.Override
      public MarkerDiffSnapshotVo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MarkerDiffSnapshotVo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MarkerDiffSnapshotVo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MarkerDiffSnapshotVo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MarkerDiffSnapshotVoListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.yuanshen.data.proto.MarkerDiffSnapshotVoList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    java.util.List<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo> 
        getSnapshotsList();
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo getSnapshots(int index);
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    int getSnapshotsCount();
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    java.util.List<? extends site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder> 
        getSnapshotsOrBuilderList();
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder getSnapshotsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code site.yuanshen.data.proto.MarkerDiffSnapshotVoList}
   */
  public  static final class MarkerDiffSnapshotVoList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.yuanshen.data.proto.MarkerDiffSnapshotVoList)
      MarkerDiffSnapshotVoListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MarkerDiffSnapshotVoList.newBuilder() to construct.
    private MarkerDiffSnapshotVoList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MarkerDiffSnapshotVoList() {
      snapshots_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MarkerDiffSnapshotVoList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MarkerDiffSnapshotVoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                snapshots_ = new java.util.ArrayList<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo>();
                mutable_bitField0_ |= 0x00000001;
              }
              snapshots_.add(
                  input.readMessage(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          snapshots_ = java.util.Collections.unmodifiableList(snapshots_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.class, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.Builder.class);
    }

    public static final int SNAPSHOTS_FIELD_NUMBER = 1;
    private java.util.List<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo> snapshots_;
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    public java.util.List<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo> getSnapshotsList() {
      return snapshots_;
    }
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    public java.util.List<? extends site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder> 
        getSnapshotsOrBuilderList() {
      return snapshots_;
    }
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    public int getSnapshotsCount() {
      return snapshots_.size();
    }
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo getSnapshots(int index) {
      return snapshots_.get(index);
    }
    /**
     * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
     */
    public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder getSnapshotsOrBuilder(
        int index) {
      return snapshots_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < snapshots_.size(); i++) {
        output.writeMessage(1, snapshots_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < snapshots_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, snapshots_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList)) {
        return super.equals(obj);
      }
      site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList other = (site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList) obj;

      if (!getSnapshotsList()
          .equals(other.getSnapshotsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSnapshotsCount() > 0) {
        hash = (37 * hash) + SNAPSHOTS_FIELD_NUMBER;
        hash = (53 * hash) + getSnapshotsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.yuanshen.data.proto.MarkerDiffSnapshotVoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.yuanshen.data.proto.MarkerDiffSnapshotVoList)
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.class, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.Builder.class);
      }

      // Construct using site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSnapshotsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (snapshotsBuilder_ == null) {
          snapshots_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          snapshotsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_descriptor;
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList getDefaultInstanceForType() {
        return site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.getDefaultInstance();
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList build() {
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList buildPartial() {
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList result = new site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList(this);
        int from_bitField0_ = bitField0_;
        if (snapshotsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            snapshots_ = java.util.Collections.unmodifiableList(snapshots_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.snapshots_ = snapshots_;
        } else {
          result.snapshots_ = snapshotsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList) {
          return mergeFrom((site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList other) {
        if (other == site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList.getDefaultInstance()) return this;
        if (snapshotsBuilder_ == null) {
          if (!other.snapshots_.isEmpty()) {
            if (snapshots_.isEmpty()) {
              snapshots_ = other.snapshots_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSnapshotsIsMutable();
              snapshots_.addAll(other.snapshots_);
            }
            onChanged();
          }
        } else {
          if (!other.snapshots_.isEmpty()) {
            if (snapshotsBuilder_.isEmpty()) {
              snapshotsBuilder_.dispose();
              snapshotsBuilder_ = null;
              snapshots_ = other.snapshots_;
              bitField0_ = (bitField0_ & ~0x00000001);
              snapshotsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSnapshotsFieldBuilder() : null;
            } else {
              snapshotsBuilder_.addAllMessages(other.snapshots_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo> snapshots_ =
        java.util.Collections.emptyList();
      private void ensureSnapshotsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          snapshots_ = new java.util.ArrayList<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo>(snapshots_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder> snapshotsBuilder_;

      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public java.util.List<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo> getSnapshotsList() {
        if (snapshotsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(snapshots_);
        } else {
          return snapshotsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public int getSnapshotsCount() {
        if (snapshotsBuilder_ == null) {
          return snapshots_.size();
        } else {
          return snapshotsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo getSnapshots(int index) {
        if (snapshotsBuilder_ == null) {
          return snapshots_.get(index);
        } else {
          return snapshotsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder setSnapshots(
          int index, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo value) {
        if (snapshotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnapshotsIsMutable();
          snapshots_.set(index, value);
          onChanged();
        } else {
          snapshotsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder setSnapshots(
          int index, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder builderForValue) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          snapshots_.set(index, builderForValue.build());
          onChanged();
        } else {
          snapshotsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder addSnapshots(site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo value) {
        if (snapshotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnapshotsIsMutable();
          snapshots_.add(value);
          onChanged();
        } else {
          snapshotsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder addSnapshots(
          int index, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo value) {
        if (snapshotsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnapshotsIsMutable();
          snapshots_.add(index, value);
          onChanged();
        } else {
          snapshotsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder addSnapshots(
          site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder builderForValue) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          snapshots_.add(builderForValue.build());
          onChanged();
        } else {
          snapshotsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder addSnapshots(
          int index, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder builderForValue) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          snapshots_.add(index, builderForValue.build());
          onChanged();
        } else {
          snapshotsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder addAllSnapshots(
          java.lang.Iterable<? extends site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo> values) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, snapshots_);
          onChanged();
        } else {
          snapshotsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder clearSnapshots() {
        if (snapshotsBuilder_ == null) {
          snapshots_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          snapshotsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public Builder removeSnapshots(int index) {
        if (snapshotsBuilder_ == null) {
          ensureSnapshotsIsMutable();
          snapshots_.remove(index);
          onChanged();
        } else {
          snapshotsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder getSnapshotsBuilder(
          int index) {
        return getSnapshotsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder getSnapshotsOrBuilder(
          int index) {
        if (snapshotsBuilder_ == null) {
          return snapshots_.get(index);  } else {
          return snapshotsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public java.util.List<? extends site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder> 
           getSnapshotsOrBuilderList() {
        if (snapshotsBuilder_ != null) {
          return snapshotsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(snapshots_);
        }
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder addSnapshotsBuilder() {
        return getSnapshotsFieldBuilder().addBuilder(
            site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.getDefaultInstance());
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder addSnapshotsBuilder(
          int index) {
        return getSnapshotsFieldBuilder().addBuilder(
            index, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.getDefaultInstance());
      }
      /**
       * <code>repeated .site.yuanshen.data.proto.MarkerDiffSnapshotVo snapshots = 1;</code>
       */
      public java.util.List<site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder> 
           getSnapshotsBuilderList() {
        return getSnapshotsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder> 
          getSnapshotsFieldBuilder() {
        if (snapshotsBuilder_ == null) {
          snapshotsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVo.Builder, site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoOrBuilder>(
                  snapshots_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          snapshots_ = null;
        }
        return snapshotsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:site.yuanshen.data.proto.MarkerDiffSnapshotVoList)
    }

    // @@protoc_insertion_point(class_scope:site.yuanshen.data.proto.MarkerDiffSnapshotVoList)
    private static final site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList();
    }

    public static site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MarkerDiffSnapshotVoList>
        PARSER = new com.google.protobuf.AbstractParser<MarkerDiffSnapshotVoList>() {
      @java.lang.Override
      public MarkerDiffSnapshotVoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MarkerDiffSnapshotVoList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MarkerDiffSnapshotVoList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MarkerDiffSnapshotVoList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public site.yuanshen.data.proto.MarkerDiffSnapshotVoOuterClass.MarkerDiffSnapshotVoList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032MarkerDiffSnapshotVo.proto\022\030site.yuans" +
      "hen.data.proto\"3\n\024MarkerDiffSnapshotVo\022\017" +
      "\n\007version\030\001 \001(\004\022\n\n\002id\030\002 \001(\004\"]\n\030MarkerDif" +
      "fSnapshotVoList\022A\n\tsnapshots\030\001 \003(\0132..sit" +
      "e.yuanshen.data.proto.MarkerDiffSnapshot" +
      "Vob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVo_descriptor,
        new java.lang.String[] { "Version", "Id", });
    internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_yuanshen_data_proto_MarkerDiffSnapshotVoList_descriptor,
        new java.lang.String[] { "Snapshots", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
