// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SysUserSmallVo.proto
// Protobuf Java Version: 4.33.0

package site.yuanshen.data.proto;

@com.google.protobuf.Generated
public final class SysUserSmallVoOuterClass extends com.google.protobuf.GeneratedFile {
  private SysUserSmallVoOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "SysUserSmallVoOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SysUserSmallVoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.yuanshen.data.proto.SysUserSmallVo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string nickname = 2;</code>
     * @return The nickname.
     */
    java.lang.String getNickname();
    /**
     * <code>string nickname = 2;</code>
     * @return The bytes for nickname.
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <code>string qq = 3;</code>
     * @return The qq.
     */
    java.lang.String getQq();
    /**
     * <code>string qq = 3;</code>
     * @return The bytes for qq.
     */
    com.google.protobuf.ByteString
        getQqBytes();

    /**
     * <code>optional string phone = 4;</code>
     * @return Whether the phone field is set.
     */
    boolean hasPhone();
    /**
     * <code>optional string phone = 4;</code>
     * @return The phone.
     */
    java.lang.String getPhone();
    /**
     * <code>optional string phone = 4;</code>
     * @return The bytes for phone.
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>optional string logo = 5;</code>
     * @return Whether the logo field is set.
     */
    boolean hasLogo();
    /**
     * <code>optional string logo = 5;</code>
     * @return The logo.
     */
    java.lang.String getLogo();
    /**
     * <code>optional string logo = 5;</code>
     * @return The bytes for logo.
     */
    com.google.protobuf.ByteString
        getLogoBytes();

    /**
     * <code>optional string remark = 15;</code>
     * @return Whether the remark field is set.
     */
    boolean hasRemark();
    /**
     * <code>optional string remark = 15;</code>
     * @return The remark.
     */
    java.lang.String getRemark();
    /**
     * <code>optional string remark = 15;</code>
     * @return The bytes for remark.
     */
    com.google.protobuf.ByteString
        getRemarkBytes();
  }
  /**
   * Protobuf type {@code site.yuanshen.data.proto.SysUserSmallVo}
   */
  public static final class SysUserSmallVo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:site.yuanshen.data.proto.SysUserSmallVo)
      SysUserSmallVoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "SysUserSmallVo");
    }
    // Use SysUserSmallVo.newBuilder() to construct.
    private SysUserSmallVo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SysUserSmallVo() {
      username_ = "";
      nickname_ = "";
      qq_ = "";
      phone_ = "";
      logo_ = "";
      remark_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return site.yuanshen.data.proto.SysUserSmallVoOuterClass.internal_static_site_yuanshen_data_proto_SysUserSmallVo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return site.yuanshen.data.proto.SysUserSmallVoOuterClass.internal_static_site_yuanshen_data_proto_SysUserSmallVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.class, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.Builder.class);
    }

    private int bitField0_;
    public static final int USERNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object username_ = "";
    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nickname_ = "";
    /**
     * <code>string nickname = 2;</code>
     * @return The nickname.
     */
    @java.lang.Override
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      }
    }
    /**
     * <code>string nickname = 2;</code>
     * @return The bytes for nickname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QQ_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object qq_ = "";
    /**
     * <code>string qq = 3;</code>
     * @return The qq.
     */
    @java.lang.Override
    public java.lang.String getQq() {
      java.lang.Object ref = qq_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        qq_ = s;
        return s;
      }
    }
    /**
     * <code>string qq = 3;</code>
     * @return The bytes for qq.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQqBytes() {
      java.lang.Object ref = qq_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        qq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object phone_ = "";
    /**
     * <code>optional string phone = 4;</code>
     * @return Whether the phone field is set.
     */
    @java.lang.Override
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string phone = 4;</code>
     * @return The phone.
     */
    @java.lang.Override
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>optional string phone = 4;</code>
     * @return The bytes for phone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGO_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object logo_ = "";
    /**
     * <code>optional string logo = 5;</code>
     * @return Whether the logo field is set.
     */
    @java.lang.Override
    public boolean hasLogo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string logo = 5;</code>
     * @return The logo.
     */
    @java.lang.Override
    public java.lang.String getLogo() {
      java.lang.Object ref = logo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string logo = 5;</code>
     * @return The bytes for logo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLogoBytes() {
      java.lang.Object ref = logo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMARK_FIELD_NUMBER = 15;
    @SuppressWarnings("serial")
    private volatile java.lang.Object remark_ = "";
    /**
     * <code>optional string remark = 15;</code>
     * @return Whether the remark field is set.
     */
    @java.lang.Override
    public boolean hasRemark() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string remark = 15;</code>
     * @return The remark.
     */
    @java.lang.Override
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      }
    }
    /**
     * <code>optional string remark = 15;</code>
     * @return The bytes for remark.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, username_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nickname_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, nickname_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(qq_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, qq_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, phone_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, logo_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 15, remark_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, username_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nickname_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nickname_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(qq_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, qq_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, phone_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, logo_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(15, remark_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo)) {
        return super.equals(obj);
      }
      site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo other = (site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo) obj;

      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (!getNickname()
          .equals(other.getNickname())) return false;
      if (!getQq()
          .equals(other.getQq())) return false;
      if (hasPhone() != other.hasPhone()) return false;
      if (hasPhone()) {
        if (!getPhone()
            .equals(other.getPhone())) return false;
      }
      if (hasLogo() != other.hasLogo()) return false;
      if (hasLogo()) {
        if (!getLogo()
            .equals(other.getLogo())) return false;
      }
      if (hasRemark() != other.hasRemark()) return false;
      if (hasRemark()) {
        if (!getRemark()
            .equals(other.getRemark())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickname().hashCode();
      hash = (37 * hash) + QQ_FIELD_NUMBER;
      hash = (53 * hash) + getQq().hashCode();
      if (hasPhone()) {
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + getPhone().hashCode();
      }
      if (hasLogo()) {
        hash = (37 * hash) + LOGO_FIELD_NUMBER;
        hash = (53 * hash) + getLogo().hashCode();
      }
      if (hasRemark()) {
        hash = (37 * hash) + REMARK_FIELD_NUMBER;
        hash = (53 * hash) + getRemark().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.yuanshen.data.proto.SysUserSmallVo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.yuanshen.data.proto.SysUserSmallVo)
        site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return site.yuanshen.data.proto.SysUserSmallVoOuterClass.internal_static_site_yuanshen_data_proto_SysUserSmallVo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return site.yuanshen.data.proto.SysUserSmallVoOuterClass.internal_static_site_yuanshen_data_proto_SysUserSmallVo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.class, site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.Builder.class);
      }

      // Construct using site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        username_ = "";
        nickname_ = "";
        qq_ = "";
        phone_ = "";
        logo_ = "";
        remark_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return site.yuanshen.data.proto.SysUserSmallVoOuterClass.internal_static_site_yuanshen_data_proto_SysUserSmallVo_descriptor;
      }

      @java.lang.Override
      public site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo getDefaultInstanceForType() {
        return site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.getDefaultInstance();
      }

      @java.lang.Override
      public site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo build() {
        site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo buildPartial() {
        site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo result = new site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.username_ = username_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nickname_ = nickname_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.qq_ = qq_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.phone_ = phone_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.logo_ = logo_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.remark_ = remark_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo) {
          return mergeFrom((site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo other) {
        if (other == site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo.getDefaultInstance()) return this;
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getNickname().isEmpty()) {
          nickname_ = other.nickname_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getQq().isEmpty()) {
          qq_ = other.qq_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasPhone()) {
          phone_ = other.phone_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasLogo()) {
          logo_ = other.logo_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasRemark()) {
          remark_ = other.remark_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                username_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                nickname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                qq_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                phone_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                logo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 122: {
                remark_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 122
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 1;</code>
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 1;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 1;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        username_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        username_ = getDefaultInstance().getUsername();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        username_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <code>string nickname = 2;</code>
       * @return The nickname.
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nickname = 2;</code>
       * @return The bytes for nickname.
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nickname = 2;</code>
       * @param value The nickname to set.
       * @return This builder for chaining.
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nickname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string nickname = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNickname() {
        nickname_ = getDefaultInstance().getNickname();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string nickname = 2;</code>
       * @param value The bytes for nickname to set.
       * @return This builder for chaining.
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nickname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object qq_ = "";
      /**
       * <code>string qq = 3;</code>
       * @return The qq.
       */
      public java.lang.String getQq() {
        java.lang.Object ref = qq_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          qq_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string qq = 3;</code>
       * @return The bytes for qq.
       */
      public com.google.protobuf.ByteString
          getQqBytes() {
        java.lang.Object ref = qq_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          qq_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string qq = 3;</code>
       * @param value The qq to set.
       * @return This builder for chaining.
       */
      public Builder setQq(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        qq_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string qq = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQq() {
        qq_ = getDefaultInstance().getQq();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string qq = 3;</code>
       * @param value The bytes for qq to set.
       * @return This builder for chaining.
       */
      public Builder setQqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        qq_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>optional string phone = 4;</code>
       * @return Whether the phone field is set.
       */
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string phone = 4;</code>
       * @return The phone.
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string phone = 4;</code>
       * @return The bytes for phone.
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phone = 4;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        phone_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        phone_ = getDefaultInstance().getPhone();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 4;</code>
       * @param value The bytes for phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        phone_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object logo_ = "";
      /**
       * <code>optional string logo = 5;</code>
       * @return Whether the logo field is set.
       */
      public boolean hasLogo() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string logo = 5;</code>
       * @return The logo.
       */
      public java.lang.String getLogo() {
        java.lang.Object ref = logo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string logo = 5;</code>
       * @return The bytes for logo.
       */
      public com.google.protobuf.ByteString
          getLogoBytes() {
        java.lang.Object ref = logo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string logo = 5;</code>
       * @param value The logo to set.
       * @return This builder for chaining.
       */
      public Builder setLogo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        logo_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional string logo = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogo() {
        logo_ = getDefaultInstance().getLogo();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>optional string logo = 5;</code>
       * @param value The bytes for logo to set.
       * @return This builder for chaining.
       */
      public Builder setLogoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        logo_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object remark_ = "";
      /**
       * <code>optional string remark = 15;</code>
       * @return Whether the remark field is set.
       */
      public boolean hasRemark() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string remark = 15;</code>
       * @return The remark.
       */
      public java.lang.String getRemark() {
        java.lang.Object ref = remark_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remark_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string remark = 15;</code>
       * @return The bytes for remark.
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        java.lang.Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string remark = 15;</code>
       * @param value The remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemark(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        remark_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional string remark = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemark() {
        remark_ = getDefaultInstance().getRemark();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>optional string remark = 15;</code>
       * @param value The bytes for remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        remark_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:site.yuanshen.data.proto.SysUserSmallVo)
    }

    // @@protoc_insertion_point(class_scope:site.yuanshen.data.proto.SysUserSmallVo)
    private static final site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo();
    }

    public static site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SysUserSmallVo>
        PARSER = new com.google.protobuf.AbstractParser<SysUserSmallVo>() {
      @java.lang.Override
      public SysUserSmallVo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SysUserSmallVo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SysUserSmallVo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public site.yuanshen.data.proto.SysUserSmallVoOuterClass.SysUserSmallVo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_yuanshen_data_proto_SysUserSmallVo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_site_yuanshen_data_proto_SysUserSmallVo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SysUserSmallVo.proto\022\030site.yuanshen.da" +
      "ta.proto\"\232\001\n\016SysUserSmallVo\022\020\n\010username\030" +
      "\001 \001(\t\022\020\n\010nickname\030\002 \001(\t\022\n\n\002qq\030\003 \001(\t\022\022\n\005p" +
      "hone\030\004 \001(\tH\000\210\001\001\022\021\n\004logo\030\005 \001(\tH\001\210\001\001\022\023\n\006re" +
      "mark\030\017 \001(\tH\002\210\001\001B\010\n\006_phoneB\007\n\005_logoB\t\n\007_r" +
      "emarkb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_site_yuanshen_data_proto_SysUserSmallVo_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_site_yuanshen_data_proto_SysUserSmallVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_site_yuanshen_data_proto_SysUserSmallVo_descriptor,
        new java.lang.String[] { "Username", "Nickname", "Qq", "Phone", "Logo", "Remark", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
