version: 18
jobs:
- name: CI/CD
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: mvn package
    runInContainer: false
    image: '@script:builtin:maven:determine-docker-image@'
    interpreter: !DefaultInterpreter
      commands:
      - /opt/apache-maven-3.8.6/bin/mvn clean package -P dev
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: move package
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - cp genshin-map-ability/genshin-map-ability-gateway/target/genshin-map-ability-gateway-1.0.jar
        ~/genshin-map-cloud/ability/genshin-map-ability-gateway-1.0.jar
      - cp genshin-map-ability/genshin-map-ability-auth/target/genshin-map-ability-auth-1.0.jar
        ~/genshin-map-cloud/ability/genshin-map-ability-auth-1.0.jar
      - cp genshin-map-api/genshin-map-api-system/genshin-map-api-system-core/target/genshin-map-api-system-core-1.0.jar
        ~/genshin-map-cloud/api/genshin-map-api-system-core-1.0.jar
      - cp genshin-map-api/genshin-map-api-core/genshin-map-api-core-core/target/genshin-map-api-core-core-1.0.jar
        ~/genshin-map-cloud/api/genshin-map-api-core-core-1.0.jar
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: restart service
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - sh ~/genshin-map-cloud/restart.sh
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  caches:
  - key: maven-cache
    path: ~/.m2
  timeout: 3600
- name: push to Github
  jobExecutor: genshin-map-shell
  steps:
  - !PushRepository
    name: genshin-map-cloud
    remoteUrl: https://github.com/kongying-tavern/genshin-map-cloud.git
    userName: momentderek
    passwordSecret: moment-secret
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  jobDependencies:
  - jobName: CI/CD
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
