server
{
    listen 80;
    index index.php index.html index.htm default.php default.htm default.html;
    root /data;

    add_header Strict-Transport-Security "max-age=31536000";
    error_page 497 http://$host$request_uri;

    # 引用反向代理规则
    include proxy/minio-proxy.conf;

    # 禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    # 一键申请SSL证书验证目录相关设置
    location ~ \.well-known
    {
        allow all;
    }

    # 禁止在证书验证目录放入敏感文件
    if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" )
    {
        return 403;
    }

    location ~ .*\.(js|css)?$
    {
        expires 12h;
        error_log /dev/null;
        access_log /dev/null;
    }

    access_log /dev/null;
    error_log /data/log/minio-proxy.local-error.log;
}
