services:
  # Main services
  minio-proxy:
    image: gsapi/minio-proxy
    build:
      context: ${PROJECT_BASE}
      dockerfile: docker/composer/docker-compose.img-alist-build.minio-proxy.Dockerfile
  alist:
    image: gsapi/alist
    build:
      context: ${PROJECT_BASE}
      dockerfile: docker/composer/docker-compose.img-alist-build.alist.Dockerfile

  # Initialization services
  alist-init:
    image: gsapi/alist-init
    build:
      context: ${PROJECT_BASE}
      dockerfile: docker/composer/docker-compose.img-alist-build.alist-init.Dockerfile
