include:
  - docker-compose.network.yml

services:
  img-local:
    container_name: gsapi-img-local
    hostname: gsapi-img-local
    image: gsapi/img-local
    networks:
      gsapi:
        aliases:
          - img-local.local
    volumes:
      - ${DATA_DIR}/img-local:/var/www/html
    ports:
      - ${IMG_LOCAL_PORT:-8888}:80
    restart: always
