[tasks.default]
alias = "help"

## Sub-commands
# dataenv: provide data environments
[tasks.dataenv] # !! startup data environments
script = '''
#!@duckscript
!include_files ./makefile/util.env.ds ./makefile/util.docker.ds
prepare_envvars
check_env

ENV_FILE = get_env ENV_FILE
PROJECT_NAME = get_env PROJECT_NAME
docker_down "${PROJECT_NAME}" "${ENV_FILE}" "./composer/docker-compose.dataenv.yml"
docker_up "${PROJECT_NAME}" "${ENV_FILE}" "./composer/docker-compose.dataenv.yml"
'''

# help
[tasks.help]
script = '''
#!@duckscript
!include_files  ./makefile/util.env.ds ./makefile/util.help.ds
prepare_envvars

## Start script
banner = readfile ./makefile/Makefile.banner.txt
echo ${banner}

# Generate commands
cmds = get_help_commands

env_file = get_env ENV_FILE
echo Current env file:
println -c magenta " ${env_file}"

echo Available commands:
print_help_commands ${cmds}

echo What do you want? >>>
cmd_name = read
exec cargo make ${cmd_name}
'''
