#!/bin/bash

APPNAME="YSAPI SYSTEM"
FILENAME="genshin-map-api-system-core-1.0.jar"

start() {
    echo "Starting: ${APPNAME}"
    java -Dfile.encoding=UTF-8 -jar "/data/gs-api/${FILENAME}" & 2>&1
}

stop() {
    echo "Stopping: ${APPNAME}"
    ps aux | grep "${FILENAME}" | grep java | awk '{print $2}' | xargs kill -9
}

restart() {
    stop
    start
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    restart
    ;;
*)
    echo  "usage: $0 start|stop|restart"
    exit 0;
esac
exit
