spring:
  profiles:
    include:
      - nacos-dev
      - datasource-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    org.springframework:
        security: DEBUG
    site.yuanshen.data.mapper: debug
