spring:
  profiles:
    include:
      - nacos-dev
      - datasource-dev
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#logging:
#  level:
#    org.springframework:
#        security: debug
#        cache: debug
#    site.yuanshen.data.mapper: debug
logging:
  level:
    site:
      yuanshen:
        genshin:
          core: debug
        data:
          mapper: debug

