spring:
  profiles:
    include:
      - nacos-dev
      - datasource-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: '1::char'
      logic-not-delete-value: '0::char'

#logging:
#  level:
#    org.springframework:
#        security: debug
#        cache: debug
#    site.yuanshen.data.mapper: debug
logging:
  level:
    site:
      yuanshen:
        genshin:
          core: debug
