spring:
  profiles:
    include:
      - server-dev
      - nacos-dev
      - datasource-dev
      - image-dev
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    site:
      yuanshen:
        genshin:
          core: debug
    site.yuanshen.data.mapper: debug
#    org.springframework:
#        security: debug
#        cache: debug
