spring:
  cloud:
    nacos:
      server-addr: nacos.local:8848
      username: {{NACOS_USER}}
      password: {{NACOS_PASS}}
      config:
        server-addr: nacos.local:8848
        file-extension: yaml
