<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>genshin-map-api-core</artifactId>
        <groupId>site.yuanshen</groupId>
        <version>${gsapi.version}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>genshin-map-api-core-core</artifactId>

    <dependencies>
        <dependency>
            <groupId>site.yuanshen</groupId>
            <artifactId>genshin-map-commons-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>site.yuanshen</groupId>
            <artifactId>genshin-map-data-core-mapper</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>site.yuanshen</groupId>
            <artifactId>genshin-map-data-system-mapper</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!--START Auth用依赖-->
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-oauth2</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-security</artifactId>
        </dependency>
        <!--END Auth用依赖-->

        <!-- minio client -->
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.corundumstudio.socketio/netty-socketio -->
        <dependency>
            <groupId>com.corundumstudio.socketio</groupId>
            <artifactId>netty-socketio</artifactId>
            <version>2.0.13</version>
        </dependency>

        <!-- spring-boot-starter-webflux，排除其 Netty 依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
            <exclusions>
                <!-- 排除 Netty 的所有子模块 -->
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>*</artifactId> <!-- 使用通配符排除所有 Netty 模块 -->
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-buffer</artifactId>
                <version>4.1.115.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-common</artifactId>
                <version>4.1.115.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport</artifactId>
                <version>4.1.115.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-handler</artifactId>
                <version>4.1.115.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-http</artifactId>
                <version>4.1.115.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec</artifactId>
                <version>4.1.115.Final</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
