lua_shared_dict dns_cache 1m;

init_by_lua_block
{
    img_fallback_chain = dofile("/etc/nginx/conf.d/lib/img_fallback_chain.lua")
}

server
{
    listen 80;
    server_name _;

    # 引用反向代理规则
    include /etc/nginx/conf.d/minio-proxy/*.conf;

    access_log /data/log/minio-proxy.local-access.log;
    error_log /data/log/minio-proxy.local-error.log warn;
}
