spring:
  profiles:
    include:
      - common
      - nacos-prod
      - datasource-prod
  datasource:
    druid:
      # 初始连接数
      initial-size: 50
      #最大连接数
      max-active: 100
      # 最小保持连接数
      min-idle: 50
      ########## 配置StatViewServlet（监控页面），用于展示Druid的统计信息 ##########
      stat-view-servlet:
        enabled: true                   # 启用StatViewServlet
        reset-enable: false             # 清空统计数据

springdoc:
  api-docs:
    enabled: false