spring:
  profiles:
    include:
      - nacos-prod
      - datasource-prod
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    datasource:
      druid:
        # 池中某个连接的空闲时长达到 N 毫秒后, 连接池在下次检查空闲连接时，将回收该连接
        min-evictable-idle-time-millis: 300000
        # 检测超时
        validation-query-timeout: 1
        validation-query: SELECT 1
        # 申请连接时检测有效，影响性能
        test-on-borrow: false
        # 归还连接时检测有效，影响性能
        test-on-return: false
        # 循环检测有效，不影响性能
        test-while-idle: true
        # 检查空闲连接的频率，单位毫秒
        time-between-eviction-runs-millis: 10000
        # 是否缓存preparedStatement, mysql下关闭，支持游标的数据库开启
        pool-prepared-statements: false
        # 缓存preparedStatement大小，开启后建议100，-1关闭
        max-pool-prepared-statement-per-connection-size: -1
        # 初始连接数
        initial-size: 50
        #最大连接数
        max-active: 100
        # 最小保持连接数
        min-idle: 50
        async-init: false

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: '1::char'
      logic-not-delete-value: '0::char'

springdoc:
  api-docs:
    enabled: false